//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendyolDeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class TyKargoFatura
    {
        public int ID { get; set; }
        public string ShipmentPackageType { get; set; }
        public Nullable<long> ParcelUniqueId { get; set; }
        public Nullable<long> OrderNumber { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<long> Desi { get; set; }
    }
}
